### ISSUE TITLE
[Bug] isDebugEnabled = true;

### ISSUE THREAD

**Issue by black-backdoor** [BBBaden-Moodle-userscripts/potential-Points#11]
### Description

var isDebugEnabled = true;

the Debug Mode is on all the times

### Version

2.0.3

### Steps to Reproduce

open console

### Additional Context

Solution:
var isDebugEnabled = false;

**Comment by Hutch79** [comment]
tltr: debug should be false by default. Add config option to enable it.

**Comment by black-backdoor** [comment]
V: 2.0.3
