### ISSUE TITLE
[Bug] Not highlighted if isGreenBackgroundEnabled is false

### ISSUE THREAD

**Issue by Hutch79** [BBBaden-Moodle-userscripts/potential-Points#8]
### Description

If I set `isGreenBackgroundEnabled` to false, nothing gets highlighted.

```json
{
  "isGreenBackgroundEnabled": false
}
```

### Version

1.7.1

### Console output

![grafik](https://github.com/BBBaden-Moodle-userscripts/potential-Points/assets/42042811/de693207-f09a-4c96-8b81-1f794fe3fdf1)

**Comment by black-backdoor** [comment]
It seems like there is an error with the definition of variables or with scraping them.

Could you send me the website URL where the error happened?

**Comment by black-backdoor** [comment]
I am working on a debug update

**Comment by black-backdoor** [comment]
Try out the new version

now script is available from [greasyfork](https://greasyfork.org/en/scripts/477184-potential-points)

**Comment by Hutch79** [comment]
It unfortunately still doesn't work.
![grafik](https://github.com/BBBaden-Moodle-userscripts/potential-Points/assets/42042811/43126c7f-3c52-4e16-a3e4-ff3b1f6aadaf)

**Comment by black-backdoor** [comment]
With the version 2.0.3 I tried to improve the DEBUG. It would be helpful if you could send me the "DEBUG: previous_tableRow" output from the console. If the error doesn't appear, try it again with isRoundedCornersEnabled: true or change line 353

from:
if(isRoundedCornersEnabled){
      modify_previous_tableRow_elements(previous_tableRow);
}

to:
modify_previous_tableRow_elements(previous_tableRow);

**Comment by black-backdoor** [comment]
any feedback for the new DEBUG?

**Comment by Hutch79** [comment]
> any feedback for the new DEBUG?

I mean, mainly you need to know what the debug means ^^  
As long as you understand it, it's good!  

Maybe add a config option to enable it and disable it by default?

> With the version 2.0.3 I tried to improve the DEBUG. It would be helpful if you could send me the "DEBUG: previous_tableRow" output from the console.
No clue what you mean ^^'

> If the error doesn't appear, try it again with isRoundedCornersEnabled: true or [...]
I set it to true, but it didn't change a thing.
![Graphic](https://github.com/BBBaden-Moodle-userscripts/potential-Points/assets/42042811/85ea7226-a7e0-4320-b50e-1b9cb9a90459)

**Comment by black-backdoor** [comment]
you are still in version 2.0.2

**Comment by Hutch79** [comment]
v2.0.3 works.
Thx for fixing 💜
